version: '2'

services:
    db:
        image: mysql
        restart: always
        volumes:
            - "./docker/.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: europrest
    db_test:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: europrest_test
    php:
        build:
            context: docker/php7-fpm
        restart: always
        volumes:
            - ./:/var/www/htdocs
    nginx:
        build:
            context: docker/nginx
        restart: always
        volumes_from:
            - php
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx
