<?php


namespace unit;


use app\models\CategoryOption;
use app\modules\api\forms\category\UpdateCategoryForm;
use Codeception\Specify;
use Codeception\Test\Unit;

class UpdateCategoryFormTest extends Unit
{
    use Specify;

    /**
     * @var \UnitTester
     */
    protected $tester;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testSuccessLoadData()
    {
        $this->specify('It should success load data', function () {
            $data = [
                'name' => \Yii::$app->security->generateRandomString()
            ];
            $updateCategoryForm = new UpdateCategoryForm();
            $updateCategoryForm->load($data);
            verify($updateCategoryForm->name)->equals($data['name']);
        });
    }

    public function testSuccessValidate()
    {
        $this->specify('It should success validate new data', function () {
            $data = [
                'name' => \Yii::$app->security->generateRandomString(),
            ];

            $updateCategoryForm = new UpdateCategoryForm();
            $updateCategoryForm->load($data);

            verify($updateCategoryForm->validate())->equals(true);
            verify($updateCategoryForm->getFirstErrors())->equals([]);
        });
    }

    public function testValidationRequiredErrors()
    {
        $this->specify('It should have validation errors on required fields', function () {
            $data = [
                'name' => ''
            ];

            $updateCategoryForm = new UpdateCategoryForm();
            $updateCategoryForm->load($data);

            verify($updateCategoryForm->validate())->equals(false);
            verify(array_keys($updateCategoryForm->getFirstErrors()))->equals(['name']);
        });
    }
}